name: Upgrade Version
description: "Upgrade the version of the repository in the package.json"

inputs:
  github-token:
    description: "Github token"
    required: true
  github-user:
    description: "User"
    required: true
  github-ref:
    description: "Name of current ref"
    required: true
  working-directory:
    description: "Working Directory"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Set github
      id: github
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "${{ inputs.github-user }}"

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.github-ref }}
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Branch
      shell: bash
      run: git checkout ${{ inputs.github-ref }}

    - name: Update Version
      shell: bash
      run: npm run release

    - name: Push Version
      shell: bash
      run: git push
