name: Upgrade Version
description: "Upgrade the version of the repository in the package.json"

inputs:
  github-user:
    description: "User"
    required: true
  github-ref:
    description: "Name of current ref"
    required: true
  working-directory:
    description: "Working Directory"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci

    - name: Set github
      id: github
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "${{ inputs.github-user }}"

    - name: Update Version
      shell: bash
      run: npm run release

    - name: Push Version
      shell: bash
      run: git push origin "${{ inputs.github-ref }}"
