name: Upgrade Version
description: "Upgrade the version of the repository in the package.json"

inputs:
  github-token:
    description: "Github token"
    required: true
  github-user:
    description: "User"
    required: true
  github-ref:
    description: "Name of current ref"
    required: true
  fa-npm-token:
    description: "Fontawesome Token"
    required: true
  npm_token:
    description: "NPM Token"
    required: true
  working-directory:
    description: "Working Directory"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Set github
      id: github
      shell: bash
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "${{ inputs.github-user }}"

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.github-ref }}
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ inputs.fa-npm-token }}"
          npm config set '//registry.npmjs.org/:_authToken' "${{ inputs.npm_token }}"
          npm ci

    - name: Update Version
      shell: bash
      run: npm run release

    - name: Push Version
      shell: bash
      run: git push
